version: '3.8'
services:
  postgres: 
    image: postgres
    container_name: quer_apostar_quanto_db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=apostas_db 

  node_app:
    container_name: node_app
    build: . #Dockerfile do node se encontra na pasta atual
    ports:
      - 3000:${PORT}
    depends_on:
      - postgres # sรณ sobe quando o postgres tiver no ar;
    env_file:
      - .env